import { Geist, Geist_Mono, PT_Serif } from "next/font/google";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

import LogoutButton from "@/app/components/LogoutButton";
import LoginButton from "@/app/components/LoginButton";
import LogoComponent from "@/app/components/LogoComponent";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ptSerif = PT_Serif({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pt-serif",
});

const fontFamily = `${geistSans.variable}, ${geistMono.variable}, ${ptSerif.variable}`;

export const metadata = {
  title: "Csphere",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get("cshere_token");
  console.log("TOKEN:", token)
  return (
    <html
      lang="en"
      className={ptSerif.className}
      style={{ "--font-custom": fontFamily }}
    >
      <body className="relative font-custom">
        <header
          className="h-25 bg-gray-300 w-full flex items-center justify-between px-6 sm:px-8 lg:px-12"
          // Removed inline style attribute
        >
          {/* Left side: Logo and Desktop Navigation */}
          <div className="flex items-center space-x-4 md:space-x-8">
            <LogoComponent />
          </div>

          <div className="flex items-center space-x-3">
            <LoginButton />
            {!token && (
            <Link href="/signup">
              <button
                type="button"
                className="bg-[#E0E5E4] text-[#202A29] px-6 py-3 rounded-lg hover:bg-[#CCD3D2] text-base font-large"
              >
                Sign Up
              </button>
              </Link>
            )}
            <div className="md:hidden">
              <button
                type="button"
                // onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)} // Add state toggle later
                className="inline-flex items-center justify-center p-2 rounded-md text-[#202A29] hover:text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" // Example styling
                aria-controls="mobile-menu"
                aria-expanded="false" // This should be dynamic based on state {isMobileMenuOpen}
              >
                <span className="sr-only">Open main menu</span>
                {/* Heroicon Menu (or your preferred icon) */}
                {/* {isMobileMenuOpen ? <XIcon/> : <MenuIcon/>} */}
                <svg
                  className="h-6 w-6"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  aria-hidden="true"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M4 6h16M4 12h16m-7 6h7"
                  />
                </svg>
              </button>
            </div>
          </div>

          {/* --- Mobile Menu (Needs State Management) --- */}
          {/* This section would be conditionally rendered based on isMobileMenuOpen state */}
          {/* <div className={`${isMobileMenuOpen ? 'block' : 'hidden'} md:hidden`} id="mobile-menu">
        <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-gray-300 absolute left-0 right-0 shadow-lg">
          <a href="#" className="block px-3 py-2 rounded-md text-base font-medium text-[#202A29] hover:text-gray-700 hover:bg-gray-100">Solutions</a>
          <a href="#" className="block px-3 py-2 rounded-md text-base font-medium text-[#202A29] hover:text-gray-700 hover:bg-gray-100">Industries</a>
          <a href="#" className="block px-3 py-2 rounded-md text-base font-medium text-[#202A29] hover:text-gray-700 hover:bg-gray-100">About us</a>
          <a href="#" className="block px-3 py-2 rounded-md text-base font-medium text-[#202A29] hover:text-gray-700 hover:bg-gray-100">Contact</a>
        </div>
      </div> */}
        </header>
        {children}

        {/* <footer className=" text-white  mt-8 absolute bottom-0 w-full ">
          <div className="  text-center">
            <p>&copy; 2025 Cphere. All rights reserved.</p>
          </div>
        </footer> */}
        {/* <Toaster className="bg-white text-red-200" /> */}
      </body>
    </html>
  );
}
