FROM python:3.10-slim

RUN apt update && apt install -y git
#RUN apk add --no-cache --update openssh-client # in short

# Set the working directory in the container
WORKDIR /app


# Clone the "frontend" directory from your GitHub repositorydd the SSH public keys of the Git server to the known hosts (here, github.com)
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN apt-get update -y
RUN apt-get install -y python3-dev build-essential
RUN apt-get install -y default-libmysqlclient-dev pkg-config

RUN apt-get install -y libpq-dev

# bust the cache everytime
COPY timedatenow.txt /etc/


RUN --mount=type=ssh git clone 'git@github.com:TipTop-Tech/csphere-app.git' /app

WORKDIR /app/backend

RUN pip install -r requirements.txt






CMD ["uvicorn", "app.api.main:app", "--reload"]