"""correct second  revision

Revision ID: 2605a0660461
Revises: 252cbf6f298a
Create Date: 2025-06-09 14:48:02.550674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '2605a0660461'
down_revision: Union[str, None] = '252cbf6f298a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='NOW()', nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('first_saved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('content_id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('content_ai',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('content_item',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_item')
    op.drop_table('content_ai')
    op.drop_table('content')
    op.drop_table('users')
    # ### end Alembic commands ###
