"""adding in tables for category insertions

Revision ID: 5e0dbc6441e8
Revises: bee00dbc3731
Create Date: 2025-08-07 10:08:50.747846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0dbc6441e8'
down_revision: Union[str, None] = 'bee00dbc3731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_modified', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('content_category',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id', 'category_id')
    )
    # ### end Alembic commands ###sss


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_category')
    op.drop_table('category')
    # ### end Alembic commands ###
