"""fixing read column upgrade for the content tabele

Revision ID: 71eae202f2e1
Revises: c82c3186beab
Create Date: 2025-06-24 15:28:18.173235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71eae202f2e1'
down_revision: Union[str, None] = 'c82c3186beab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
