"""moving over the read value

Revision ID: bb902acb986a
Revises: e1f5eb169fc3
Create Date: 2025-11-04 14:42:02.944690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb902acb986a'
down_revision: Union[str, None] = 'e1f5eb169fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'read')
    op.add_column('content_item', sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_item', 'read')
    op.add_column('content', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
