"""folder logic fix

Revision ID: bee00dbc3731
Revises: e5f7f6e310a0
Create Date: 2025-07-09 21:06:36.968569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
#Note: Changes made here, may be inconsistent with real migration up
revision: str = 'bee00dbc3731'
down_revision: Union[str, None] = 'e5f7f6e310a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('folder_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("'2025-07-10 01:05:43.93076'::timestamp without time zone"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.folder_id'], name='folder_parent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='folder_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id', name='folder_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('folder_item',
    sa.Column('folder_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text("'2025-07-10 01:05:43.93076'::timestamp without time zone"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.folder_id'], name=op.f('folder_item_folder_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'content_id'], ['content_item.user_id', 'content_item.content_id'], name=op.f('folder_item_user_id_content_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_item_id', name=op.f('folder_item_pkey'))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_item')
    op.drop_table('folder')
    
    # ### end Alembic commands ###
