"""added read column to indiciate is the user has opened the tab

Revision ID: c82c3186beab
Revises: 2605a0660461
Create Date: 2025-06-24 15:21:20.208125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82c3186beab'
down_revision: Union[str, None] = '2605a0660461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('read', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'read')
    # ### end Alembic commands ###
