"""removing user id connection from content table

Revision ID: e1f5eb169fc3
Revises: 5e0dbc6441e8
Create Date: 2025-11-04 14:30:05.824131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f5eb169fc3'
down_revision: Union[str, None] = '5e0dbc6441e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('content_user_id_fkey'), 'content', type_='foreignkey')
    op.drop_column('content', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('content_user_id_fkey'), 'content', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
